module dev.civl.abc {
    requires dev.civl.sarl;
    requires transitive antlr3runtime;
    exports dev.civl.abc.main;
    exports dev.civl.abc.ast.IF;
    exports dev.civl.abc.ast.node.IF;
    exports dev.civl.abc.ast.node.IF.acsl;
    exports dev.civl.abc.ast.node.IF.compound;
    exports dev.civl.abc.ast.node.IF.declaration;
    exports dev.civl.abc.ast.node.IF.expression;
    exports dev.civl.abc.ast.node.IF.label;
    exports dev.civl.abc.ast.node.IF.omp;
    exports dev.civl.abc.ast.node.IF.statement;
    exports dev.civl.abc.ast.node.IF.type;
    exports dev.civl.abc.ast.value.IF;
    exports dev.civl.abc.ast.type.IF;
    exports dev.civl.abc.ast.entity.IF;
    exports dev.civl.abc.ast.conversion.IF;
    exports dev.civl.abc.front.IF;
    exports dev.civl.abc.token.IF;
    exports dev.civl.abc.config.IF;
    exports dev.civl.abc.transform.IF;
    exports dev.civl.abc.analysis.IF;
    exports dev.civl.abc.err.IF;
    exports dev.civl.abc.program.IF;
    exports dev.civl.abc.util.IF;
    exports dev.civl.abc.ast.node.common.acsl;
    exports dev.civl.abc.transform.common;
    exports dev.civl.abc.analysis.pointsTo.IF;
    exports dev.civl.abc.ast.util;
    exports dev.civl.abc.front.c.parse;
    exports dev.civl.abc.ast.type.common;
    exports dev.civl.abc.front.c.preproc;
    exports dev.civl.abc.ast.node.common.expression;
}
