cnb: driver.cvl naive_mxm.f block_mxm.f
	civl compare -spec driver.cvl naive_mxm.f -impl driver.cvl block_mxm.f

cnb2: driver.cvl naive_mxm.f block_mxm.f
	civl compare -spec driver.cvl naive_mxm.f -impl driver.cvl block_mxm_bad.f
