
all: dotProduct1 dotProduct_critical dotProduct_orphan

dotProduct1: dotProduct1.cvl
	civl verify dotProduct1.cvl

dotProduct_critical: dotProduct_critical.cvl
	civl verify dotProduct_critical.cvl

dotProduct_orphan: dotProduct_orphan.cvl
	civl verify dotProduct_orphan.cvl

