/*******************************************************************************
 * Copyright (c) 2013 Stephen F. Siegel, University of Delaware.
 * 
 * This file is part of SARL.
 * 
 * SARL is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 * 
 * SARL is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with SARL. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package dev.civl.sarl.prove.IF;

import java.nio.file.Path;

import dev.civl.sarl.IF.expr.BooleanExpression;

/**
 * A factory for producing instances of {@link TheoremProver}. Each instance of
 * {@link TheoremProver} contains a specific, fixed "context". The context is a
 * boolean symbolic expression. It is the assumption that is used for all
 * queries asked of that theorem prover. In symbolic execution, the context is
 * typically the "path condition". Hence a distinct theorem prover is generated
 * for each path condition.
 * 
 * @author Stephen F. Siegel
 */
public interface TheoremProverFactory {

	/**
	 * The directory that can be used for files generated by the theory provers
	 * created by this factory.
	 * 
	 * @return the directory
	 */
	Path workingDirectory();

	/**
	 * Returns a new instance of {@link TheoremProver} with the given context.
	 * 
	 * @param context boolean expression assumed to hold
	 * @return a theorem prover operating under the given context
	 */
	TheoremProver newProver(BooleanExpression context);

	/**
	 * Returns a new instance of {@link TheoremProver} with the given context.
	 * 
	 * @param context        boolean expression assumed to hold
	 * @param logicFunctions A list of {@link ProverFunctionInterpretation}s. Some
	 *                       provers support factoring the common and complex parts
	 *                       into logic functions (e.g. z3, cvc4)
	 * @return a theorem prover operating under the given context
	 */
	TheoremProver newProver(BooleanExpression context, ProverFunctionInterpretation logicFunctions[]);
}
