package dev.civl.mc.model.common;

import dev.civl.mc.model.IF.CIVLException;
import dev.civl.mc.model.IF.CIVLSource;

public class ModelFactoryException extends CIVLException {

	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = 1L;

	public ModelFactoryException(String message, CIVLSource source) {
		super(message, source);
	}

}
